config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-dashboard:
      branch: main
      repo: https://github.com/ai4os/ai4-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amaranth-quail.sh
        container: qc.acc_pokey-viridian-fousek
  QC.Doc:
    repos:
      github.com/ai4os/ai4-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ochre-urchin.sh
        container: qc.doc_pokey-goldenrod-beaver
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cornflower-clam.sh
        container: qc.doc_tasty-turquoise-sheepdog
  QC.Lic:
    repos:
      github.com/ai4os/ai4-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-asparagus-moth.sh
        container: qc.lic_lousy-russet-akbash
  QC.Ver:
    repos:
      github.com/ai4os/ai4-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-khaki-audemer.sh
        container: qc.ver_grumpy-brown-koala
timeout: 5400
