config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-dashboard:
      branch: main
      repo: https://github.com/ai4os/ai4-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-heliotrope-rottweiler.sh
        container: qc.acc_gloppy-lilac-budgerigar
  QC.Doc:
    repos:
      github.com/ai4os/ai4-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-linen-barracuda.sh
        container: qc.doc_slaphappy-burgundy-gar
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-smalt-donkey.sh
        container: qc.doc_flabby-razzmatazz-tarsier
  QC.Lic:
    repos:
      github.com/ai4os/ai4-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-brass-quoll.sh
        container: qc.lic_cheeky-saffron-chamois
  QC.Ver:
    repos:
      github.com/ai4os/ai4-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-salmon-mongoose.sh
        container: qc.ver_leaky-black-spitz
timeout: 5400
