config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-dashboard:
      branch: main
      repo: https://github.com/ai4os/ai4-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lilac-yak.sh
        container: qc.acc_hazy-cornflower-jellyfish
  QC.Doc:
    repos:
      github.com/ai4os/ai4-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-scarlet-gharial.sh
        container: qc.doc_shaggy-violet-bullfrog
      github.com/ai4os/ai4-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cerise-paradise.sh
        container: qc.doc_crabby-silver-maltese
  QC.Lic:
    repos:
      github.com/ai4os/ai4-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cornflower-bison.sh
        container: qc.lic_flimsy-cornflower-woodpecker
  QC.Ver:
    repos:
      github.com/ai4os/ai4-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-sapphire-tapir.sh
        container: qc.ver_scanty-sangria-barb
timeout: 5400
